apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: prod  # Namespace in which to deploy the Nginx container
spec:
  replicas: 1  # Deploy one replica of the Nginx container
  selector:
    matchLabels:
      app: nginx  # Used to match the Deployment to the Pods
  template:
    metadata:
      labels:
        app: nginx  # This label is used by the Service to match Pods
    spec:
      containers:
      - name: nginx  # Container name
        image: acrnew1.azurecr.io/my-app:${{ github.sha }}  # Replace with your image and tag
        ports:
        - containerPort: 80  # Exposing port 80 from the container
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: prod  # Namespace to match the deployment
spec:
  selector:
    app: nginx  # Match the Pods that have the app: nginx label
  ports:
    - protocol: TCP
      port: 80  # Exposing port 80 externally
      targetPort: 80  # Target port inside the container
  type: LoadBalancer  # Expose the service through a LoadBalancer
