apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydockerapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydockerapi
  template:
    metadata:
      labels:
        app: mydockerapi
    spec:
      containers:
      - name: mydockerapi
        image: myacrrepo.azurecr.io/mydockerapi:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mydockerapi-service
spec:
  selector:
    app: mydockerapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
