name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  # Job for building and pushing the Docker image
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Build and Push Docker Image to ACR
      run: |
        docker build -t myacrrepo.azurecr.io/mydockerapi:v1 .
        docker push myacrrepo.azurecr.io/mydockerapi:v1

  # Job for deploying to AKS
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Set up AKS Credentials
      uses: azure/aks-set-context@v1
      with:
        resource-group: myresourcegroup
        cluster-name: myakscluster

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
