on: [push]

permissions:
  id-token: write  # Allow GitHub Actions to request an ID token
  contents: read   # Allow reading repository contents
env:
  REGISTRY_NAME: acrnew1
  CLUSTER_NAME: prod-aks-cluster
  CLUSTER_RESOURCE_GROUP: rg-prod
  NAMESPACE: prod
  IMAGE_NAME: my-app
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@master

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.5.0"  # Set your desired Terraform version
        
   # Log into Azure using the service principal credentials
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{secrets.AZURE_AD_CLIENT_ID}}
        client-secret: ${{secrets.AZURE_AD_CLIENT_SECRET}}
        tenant-id: ${{secrets.AZURE_AD_TENANT_ID}}
        subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

    # Docker login to Azure container registry
    - name: Docker login to Azure container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{env.REGISTRY_NAME}}.azurecr.io
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}


    - name: Build and Push Docker image
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
